/*
 * generated by Xtext
 */
package org.eclipse.b3;

/**
 * Use this class to register components to be used within the IDE.
 */
public class BeeLangUiModule extends org.eclipse.b3.AbstractBeeLangUiModule {

}
