/*
* generated by Xtext
*/
package org.eclipse.b3.contentassist;

import org.eclipse.b3.contentassist.AbstractBeeLangProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class BeeLangProposalProvider extends AbstractBeeLangProposalProvider {

}
